version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: contest-join
      POSTGRES_PASSWORD: contest-join

  # this second PostgresSQL is used when running test
  postgres-db-test:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: contest-join
      POSTGRES_USER: contest-join
      POSTGRES_PASSWORD: contest-join
